# Generated by Django 5.2.9 on 2026-02-27 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lng_planner', '0002_alter_cargo_options_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='is_master',
            field=models.BooleanField(default=False, help_text='Master simulation loaded from SAP'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='last_sap_sync',
            field=models.DateTimeField(blank=True, help_text='Last time master data was synced from SAP', null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='sap_api_url',
            field=models.URLField(blank=True, help_text='SAP API URL for refreshing master data'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL),
        ),
    ]
