# Generated by Django 5.2.9 on 2026-02-25 10:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_url', models.URLField()),
                ('supplier_table', models.CharField(default='suppliers', max_length=100)),
                ('supplier_name_col', models.CharField(max_length=100)),
                ('supplier_daily_supply_col', models.CharField(max_length=100)),
                ('supplier_from_date_col', models.CharField(max_length=100)),
                ('supplier_to_date_col', models.CharField(max_length=100)),
                ('cargo_table', models.CharField(default='cargos', max_length=100)),
                ('cargo_name_col', models.CharField(max_length=100)),
                ('cargo_date_col', models.CharField(max_length=100)),
                ('cargo_amount_col', models.CharField(max_length=100)),
                ('customer_table', models.CharField(default='customers', max_length=100)),
                ('customer_name_col', models.CharField(max_length=100)),
                ('customer_daily_demand_col', models.CharField(max_length=100)),
                ('customer_from_date_col', models.CharField(max_length=100)),
                ('customer_to_date_col', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Simulation', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('opening_inventory', models.FloatField(help_text='Total opening inventory (MT)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('opening_inventory', models.FloatField(help_text='MT', validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='lng_planner.simulation')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('simulation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('daily_demand', models.FloatField(help_text='MT per day', validators=[django.core.validators.MinValueValidator(0)])),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(help_text='Plant supplying to customer', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='lng_planner.plant')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='lng_planner.simulation')),
            ],
            options={
                'ordering': ['plant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('amount', models.FloatField(help_text='MT', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(help_text='Plant receiving cargo', on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='lng_planner.plant')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='lng_planner.simulation')),
            ],
            options={
                'ordering': ['plant', 'delivery_date', 'cargo_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('daily_supply', models.FloatField(help_text='MT per day', validators=[django.core.validators.MinValueValidator(0)])),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(help_text='Plant receiving supply', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='lng_planner.plant')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='lng_planner.simulation')),
            ],
            options={
                'ordering': ['plant', 'name'],
            },
        ),
    ]
