# Generated by Django 5.2.9 on 2026-02-26 06:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lng_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['delivery_date', 'plant__name', 'cargo_name']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['plant__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['plant__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='opening_inventory',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='lng_planner.plant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='lng_planner.plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='lng_planner.plant'),
        ),
        migrations.RemoveField(
            model_name='plant',
            name='opening_inventory',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='simulation',
        ),
        migrations.CreateModel(
            name='PlantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_inventory', models.FloatField(help_text='MT', validators=[django.core.validators.MinValueValidator(0)])),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lng_planner.plant')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_inventories', to='lng_planner.simulation')),
            ],
            options={
                'ordering': ['plant__name'],
                'unique_together': {('simulation', 'plant')},
            },
        ),
    ]
