# Generated by Django 6.0.6 on 2026-06-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lng_planner', '0003_simulation_is_master_simulation_last_sap_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preference',
            field=models.IntegerField(default=1, help_text='Lower values are served first'),
        ),
    ]
