# Generated by Django 6.0.6 on 2026-06-11 05:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lng_planner', '0004_customer_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('daily_demand', models.FloatField(help_text='MT per day', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lng_planner.customer')),
            ],
            options={
                'ordering': ['customer__name', 'from_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('daily_supply', models.FloatField(help_text='MT per day', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lng_planner.supplier')),
            ],
            options={
                'ordering': ['supplier__name', 'from_date'],
            },
        ),
    ]
