# Generated by Django 6.0.6 on 2026-06-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lng_planner', '0005_customerschedule_supplierschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierschedule',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='CustomerSchedule',
        ),
        migrations.DeleteModel(
            name='SupplierSchedule',
        ),
    ]
