# Generated by Django 6.0.6 on 2026-06-18 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lng_planner', '0007_alter_customer_options_alter_supplier_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for this version', max_length=200)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Integration'), ('SIMULATION', 'Simulation Publish')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of changes')),
                ('is_active', models.BooleanField(default=False, help_text='Currently active master version')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_versions', to='lng_planner.simulation')),
            ],
            options={
                'verbose_name': 'Master Version',
                'verbose_name_plural': 'Master Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='simulation',
            name='master_version',
            field=models.ForeignKey(blank=True, help_text='Master version this simulation was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='lng_planner.masterversion'),
        ),
    ]
