# Generated by Django 6.0.6 on 2026-06-19 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lng_planner', '0008_masterversion_simulation_master_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdate',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier serving this customer during this date range', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_date_ranges', to='lng_planner.supplier'),
        ),
    ]
