# Generated by Django 6.0.6 on 2026-06-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lng_planner', '0010_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinerydate',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier serving this refinery during this date range', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refinery_date_ranges', to='lng_planner.supplier'),
        ),
    ]
